var tree = [["Maths","Maths.html","",
                [["Algebra","Maths\/Algebra.html","",
                [["Matrix","Maths\/Algebra\/Matrix.html","",
                [        ]]        ]],["Arithmetic","Maths\/Arithmetic.html","",
                [["Helper","Maths\/Arithmetic\/Helper.html","",
                [        ]]        ]],["Geometry","Maths\/Geometry.html","",
                [["AbstractGeometricObject","Maths\/Geometry\/AbstractGeometricObject.html"," < AbstractCartesianObject",
                [        ]],["Angle","Maths\/Geometry\/Angle.html"," < AbstractGeometricObject",
                [        ]],["Circle","Maths\/Geometry\/Circle.html"," < AbstractGeometricObject",
                [        ]],["Line","Maths\/Geometry\/Line.html"," < AbstractGeometricObject",
                [        ]],["Point","Maths\/Geometry\/Point.html"," < Point3D",
                [        ]],["Quadrilateral","Maths\/Geometry\/Quadrilateral.html"," < AbstractGeometricObject",
                [        ]],["Rectangle","Maths\/Geometry\/Rectangle.html"," < Quadrilateral",
                [        ]],["Segment","Maths\/Geometry\/Segment.html"," < Line",
                [        ]],["Triangle","Maths\/Geometry\/Triangle.html"," < AbstractGeometricObject",
                [        ]],["TriangleRectangle","Maths\/Geometry\/TriangleRectangle.html"," < Rectangle",
                [        ]],["Vector","Maths\/Geometry\/Vector.html"," < Segment",
                [        ]]        ]],["Helper","Maths\/Helper.html","",
                [["JSXgraph","Maths\/Helper\/JSXgraph.html","",
                [        ]]        ]],["AbstractCartesianObject","Maths\/AbstractCartesianObject.html","",
                [        ]],["Cartesian1DInterface","Maths\/Cartesian1DInterface.html","",
                [        ]],["Cartesian2DInterface","Maths\/Cartesian2DInterface.html","",
                [        ]],["Cartesian3DInterface","Maths\/Cartesian3DInterface.html","",
                [        ]],["CartesianInterface","Maths\/CartesianInterface.html","",
                [        ]],["Maths","Maths\/Maths.html","",
                [        ]],["Point1D","Maths\/Point1D.html"," < AbstractCartesianObject",
                [        ]],["Point2D","Maths\/Point2D.html"," < Point1D",
                [        ]],["Point3D","Maths\/Point3D.html"," < Point2D",
                [        ]],["PointInterface","Maths\/PointInterface.html","",
                [        ]]        ]]        ]

